build:
  maxIssues: 0

config:
  validation: true

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

complexity:
  LongMethod:
    threshold: 150
    ignoreAnnotated: ['Composable']
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 10
    ignoreAnnotated: ['Composable']
  CyclomaticComplexMethod:
    threshold: 18
  TooManyFunctions:
    thresholdInClasses: 18

naming:
  FunctionNaming:
    functionPattern: '[a-z][A-Za-z0-9]*'
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Z0-9_]*'
  MatchingDeclarationName:
    active: false

style:
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 140
  ReturnCount:
    active: false
  UnusedParameter:
    active: false
  WildcardImport:
    active: true

formatting:
  active: true
  Indentation:
    active: true
    indentSize: 4
  MaximumLineLength:
    active: true
    maxLineLength: 140
  NoWildcardImports:
    active: true
